apiVersion: v1
kind: Pod
metadata:
  name: tcpdump-n
spec:
  containers:
  - command:
    - bin/sh
    - -c
    - while true; do sleep 1000000; done;
    image: royov/tcpdump-n
    name: tcpdump-n
    volumeMounts:
    - mountPath: /tmp
      name: volume
  hostNetwork: true
  nodeName: worker1
  volumes:
  - hostPath:
      path: /home/vagrant/out/
    name: volume
